[package]
name = "oxide"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "^0.12.1"
anyhow = "1"
atty = "^0.2.14"
clap = { version = "^3.0.6", features = ["cargo", "derive", "env", "unicode"] }
clap_complete = "^3.0.2"
dirs = "4"
heck = "^0.4.0"
regex = "1"
pulldown-cmark = "^0.9.0"
pulldown-cmark-to-cmark = "^9.0.0"
shlex = "^1.1.0"
tabwriter = "^1.2.1"
tempfile = "^3.3.0"
termbg = "^0.3.0"
terminal_size = "^0.1.17"
terminal-spinners = "^0.3.2"
thiserror = "1"
toml_edit = "^0.12.4"

[dev-dependencies]
test-context = "^0.1.3"
