[package]
name = "oxide"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
clap = { version = "^3.0.5", features = ["cargo", "derive", "env", "unicode"] }
clap_complete = "^3.0.2"
dirs = "4"
thiserror = "1"
toml_edit = "^0.12.4"
