[package]
name = "oxide"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "^0.12.1"
anyhow = "1"
atty = "^0.2.14"
clap = { version = "^3.0.5", features = ["cargo", "derive", "env", "unicode"] }
clap_complete = "^3.0.2"
dirs = "4"
shlex = "^1.1.0"
termbg = "^0.3.0"
terminal_size = "^0.1.17"
terminal-spinners = "^0.3.2"
thiserror = "1"
toml_edit = "^0.12.4"
