[package]
name = "cli-macros"
description = "Macros for our CLI generation"
version = "0.1.0"
authors = ["Jess Frazelle <jess@oxide.computer>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
cli-macros-impl = { path = "impl" }

