on:
  push:
    tags:
      - v*
name: make-release
jobs:
  makerelease:
    name: make-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0.4.4'
        with:
          credentials_json: '${{ secrets.GOOGLE_CLOUD_DL_SA }}'
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          project_id: oxide-downloads
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: rustfmt, clippy
      - name: Install deps
        shell: bash
        run: |
          sudo apt update -y && sudo apt install -y \
            clang \
            gcc \
            g++ \
            zlib1g-dev \
            libmpc-dev \
            libmpfr-dev \
            libgmp-dev
      - name: Build osxcross
        shell: bash
        run: |
          git clone https://github.com/tpoechtrager/osxcross
          cd osxcross
          wget -nc https://github.com/phracker/MacOSX-SDKs/releases/download/11.3/MacOSX11.0.sdk.tar.xz
          mv MacOSX11.0.sdk.tar.xz tarballs/
          UNATTENDED=yes ./build.sh
      - name: install toml-cli
        shell: bash
        run: |
          cargo install toml-cli
      - name: make release
        shell: bash
        run: |
          make release
      - name: move files to dir for upload
        shell: bash
        run: |
          mkdir -p releases/$(basename $(pwd))
          cp -r cross releases/$(basename $(pwd))/$(cat VERSION.txt)
      - name: 'upload binary files'
        id: upload-files
        uses: google-github-actions/upload-cloud-storage@v0.5.0
        with:
          path: releases
          destination: dl.oxide.computer
      - name: Create a Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: ${{github.workspace}}/cross/README.md

